# This is a basic workflow to help you get started with Actions

name: Jenkins

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ssh-output: ${{ steps.ssh.outputs.output }}

    steps:
      - name: Auth
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1
          IP=$(curl -s http://whatismyip.akamai.com/)
          echo "::set-output name=ip::$IP"
          aws ec2 authorize-security-group-ingress --group-name "launch-wizard-3" --protocol tcp --port 33018 --cidr $IP/32 --profile default --output text

      - name: SSH
        id: ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 54.159.142.179
          username: admin
          port: 33018
          key: ${{ secrets.ID_RSA }}
          script: build test -s

      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: python script
        env: 
          ID_RSA: ${{ secrets.ID_RSA }}
        run: |
          echo $ID_RSA > ./id_rsa
          python3 GHATest.py -a 54.159.142.179 -l admin -p 33108 -i ./id_rsa

