# This is a basic workflow to help you get started with Actions

name: Jenkins

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ssh-output: ${{ steps.ssh.outputs.output }}

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: AWS Auth
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1

      - name: Enable EC2 Access
        run: |  
          IP=$(curl -s http://whatismyip.akamai.com/)
          echo "::set-output name=ip::$IP"
          aws ec2 authorize-security-group-ingress --group-name "launch-wizard-3" --protocol tcp --port 33018 --cidr $IP/32 --profile default --output text
          
      - name: SSH Test
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh/
          cp id_rsa ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Script
        run: python GHATest.py -l admin -p 33018 -a 54.159.142.179

      - name: Revoke EC2 Access
        run: |
          aws ec2 revoke-security-group-ingress --group-name "launch-wizard-3" --protocol tcp --port 33018 --cidr $IP/32 --profile default --output text

      - name: Pass/Fail
        run: echo ${{ steps.ssh.outputs.jenkins }}
